### ISSUE TITLE
Erste Klasse erstellen

### ISSUE THREAD

**Issue by Stuni907** [CaptainKoch/Dungeons-and-Dragons#1]
**Added player one** 

Zuerst muss eine Spielfigur her. Sie wird sich im weiten Universum des Arbeitsspeicher befinden und bei jedem Neustart neu erschaffen werden.

# Der Auftrag
- Der Spieler muss wissen wer er ist
- Der Spieler sollte seine nötigen Statuswerte besitzen
- Der Spieler sollte Leben verlieren können.
- Der Spieler sollte Leben gewinnen können.
- Der Spieler sollte immer eine Rückmeldung (per Konsole) geben, falls etwas ändert.

_Waffen, Rüstungen, Magie etc. darf vorerst vernachlässigt werden_

**Comment by Stuni907** [comment]
@CaptainKoch Ist negatives Health möglich?

**Comment by CaptainKoch** [comment]
Ja ist möglich
